<?php
/**
 * Created by PhpStorm.
 * User: raphael
 * Date: 16.03.18
 * Time: 14:52
 */

class Config {
    const configArr = array(
        "db" => array(
            "db" => "musicstreaming",
            "username" => "root",
            "password" => "root",
            "host" => "127.0.0.1",
        ),
        "dbTest" => array(
            "db" => "musicstreaming",
            "username" => "ibims",
            "password" => "88c0ed80a9ee66477094",
            "host" => "127.0.0.1",
        ),
        "urls" => array(
            "base" => "http://localhost/musicstreaming/public_html",
            "id" => "id=",
            "do" => "do=",
            "register" => "?p=register",
            "registering" => "?p=registering",
            "login" => "?p=login",
            "logging_in" => "?p=logging_in",
            "logout" => "?p=logout",
            "user" => "?p=user",
            "song" => "?p=song",
            "album" => "?p=album",
            "playlist" => "?p=playlist",
            "artist" => "?p=artist",
            "search" => "?p=search",
            "add_song" => "?p=add_song",
            "add_album" => "?p=add_album",
            "add_playlist" => "?p=add_playlist",
            "add_artist" => "?p=add_artist",
            "api_overview" => "?p=api_overview",
            "api_albums" => "?p=api_albums",
            "api_artists" => "?p=api_artists",
            "api_songs" => "?p=api_songs",
            "api_playlists" => "?p=api_playlists",
            "api_genres" => "?p=api_genres",
            "uploading" => "?p=uploading",
            "githubProject" => "https://github.com/derRAV3N/musicstreaming",
            "coverDirectory" => "./content_files/images/cover/",
            "musicDirectory" => "./content_files/music/",
            "coverDirectoryInternal" => "/musicstreaming/public_html/content_files/images/cover/",
            "musicDirectoryInternal" => "/musicstreaming/public_html/content_files/music/",
        ),
        "strings" => array(
            "mainTitle" => "Music Streaming",
            "titleSeparator" => " | ",
            "madeWithLove1" => "Made with ",
            "madeWithLove2" => " by Qwatch GmbH",
            "cookieText" => "Diese Website benutzt Cookies, um dir die bestmögliche Nutzererfahrung zu bieten.",
            "cookieButton" => "Mir doch egal",
            "github" => "Dieses Projekt auf GitHub anzeigen",
            "loggedInAs" => "Eingeloggt als ",
            "logout" => "Ausloggen",
            "register" => "Registrieren",
            "login" => "Einloggen",
            "upload" => "Hochladen",
            "add" => "Hinzufügen",
            "email" => "E-Mail",
            "username" => "Nutzername",
            "password" => "Passwort",
            "repeatPassword" => "Passwort wiederholen",
            "alreadyLoggedIn" => "Du bist schon eingeloggt!",
            "alreadyRegistered" => "Du bist schon registriert!",
            "canLogoutHere" => "Hier kannst du dich ausloggen",
            "enterValidEmail" => "Gib eine gültige Mail-Adresse ein",
            "enterValidAccountname" => "Gib einen gültigen Accountnamen ein",
            "enterValidTitle" => "Gib einen gültigen Songtitel ein",
            "enterValidAlbum" => "Gib einen gültigen Albumtitel ein",
            "enterValidPlaylist" => "Gib einen gültigen Playlisttitel ein",
            "enterValidArtist" => "Gib einen gültigen Künstlernamen ein",
            "passwordHint" => "Mindestens 6 Zeichen benötigt",
            "passwordNotMatching" => "Passwörter sind nicht gleich",
            "addContent" => "Inhalte hinzufügen",
            "uploadMusic" => "Musik hochladen",
            "createAlbum" => "Album hinzufügen",
            "createPlaylist" => "Playlist erstellen",
            "createArtist" => "Künstler hinzufügen",
            "favorites" => "Favoriten",
            "api" => "API",
            "musictitles" => "Musiktitel",
            "albums" => "Alben",
            "playlists" => "Playlists",
            "musictitle" => "Musiktitel",
            "albumtitle" => "Albumtitel",
            "playlisttitle" => "Playlisttitel",
            "artisttitle" => "Künstlertitel",
            "artist" => "Künstler",
            "songs" => "Songs",
            "genres" => "Genres",
            "artists" => "Künstler",
            "overview" => "Übersicht",
            "songtext" => "Songtext...",
            "titles" => array(
                "index" => "Wie ein Lauch!",
                "login" => "Einloggen",
                "logging_in" => "Am Einloggen...",
                "register" => "Registrieren",
                "registering" => "Am Registrieren...",
                "logout" => "Am Ausloggen...",
                "song" => "Song",
                "album" => "Album",
                "artist" => "Künstler",
                "user" => "Nutzer",
                "playlist" => "Playlist",
                "search" => "Suche",
                "add_song" => "Song hochladen",
                "add_album" => "Album hinzufügen",
                "add_playlist" => "Playlist erstellen",
                "add_artist" => "Künstler hinzufügen",
                "api_overview" => "Übersicht über die API",
            ),
        ),
    );
}
